services:
  laravel.test:
    build:
      # context: ./vendor/laravel/sail/runtimes/8.5
      context: .
      dockerfile: Dockerfile.dev
      args:
        WWWGROUP: "${WWWGROUP}"
        MYSQL_CLIENT: mariadb-client
    # image: sail-8.5/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-8080}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: "1"
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
      SUPERVISOR_PHP_COMMAND: "/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --server=frankenphp --host=0.0.0.0 --admin-port=2019 --port='${APP_PORT:-80}'"
      XDG_CONFIG_HOME: "/var/www/html/config"
      XDG_DATA_HOME: "/var/www/html/data"
    volumes:
      - .:/var/www/html
    networks:
      - sail
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:lts-ubi9
    ports:
      - "${FORWARD_DB_PORT:-3307}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
    volumes:
      - "sail-mariadb:/var/lib/mysql"
      - "./vendor/laravel/sail/database/mariadb/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - "--connect"
        - "--innodb_initialized"
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge

volumes:
  sail-mariadb:
    driver: local
